spring:
  config:
    import: file:.env[.properties]
  application:
    name: tickets-backend
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  devtools:


app:
    trains:
      avgSpeed: 80
    geometry:
      srid: 4326
    api:
      prefix: /api
    stations:
      defaultWaitTime: 5