spring:
  config:
    import: file:.env[.properties]
  application:
    name: tickets-backend
  sql:
    init:
      platform: postgres
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  jmx:
    enabled: true

app:
    trains:
      avgSpeed: 80
    geometry:
      srid: 4326
    api:
      prefix: /api
    stations:
      defaultWaitTime: 5
    security:
      jwt:
        expiration: 3600
        issuer: ticket-system
        secret: ${JWT_SECRET}
    tickets:
      maxSeatsPerCoach: 80